# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [28]:
# Your solution goes here

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

response.raise_for_status()

response.encoding = "utf-8"

print(response.text[:1000])

200
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:29" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="static/oscar/favicon.

In [29]:
soup = BeautifulSoup(response.text, "html.parser")
print(type(soup))
print(soup.prettify()[:1500])

<class 'bs4.BeautifulSoup'>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>

In [37]:

books = soup.find_all("article", class_="product_pod")
first_book = soup.find("article", class_="product_pod")
display(first_book)

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [38]:
price = first_book.find(
    "p",
    class_="price_color"
).get_text(strip=True)

availability = first_book.find(
    "p",
    class_="instock availability"
).get_text(strip=True)

print("Price:", price)
print("Availability:", availability)

title = first_book.find("h3").find("a").get("title")

print("Title:", title)

Price: £51.77
Availability: In stock
Title: A Light in the Attic

In [39]:
rating = first_book.find("p", class_="star-rating").get("class")

print(rating)

rating = first_book.find("p", class_="star-rating").get("class")[1]

print("Rating:", rating)

['star-rating', 'Three']
Rating: Three

In [40]:
price_number = float(price.replace("£", ""))

print(price_number)
print(type(price_number))
rating_values = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

rating_number = rating_values[rating]

print(rating_number)
print(type(rating_number))

51.77
<class 'float'>
3
<class 'int'>

In [41]:
records = []

for book in books:
    title = book.find("h3").find("a").get("title")

    price = book.find("p", class_="price_color").get_text(strip=True)
    price = float(price.replace("£", ""))

    rating = book.find("p", class_="star-rating").get("class")[1]
    rating = rating_values[rating]

    availability = book.find("p", class_="instock availability").get_text(strip=True)

    records.append({
        "Title": title,
        "Price (£)": price,
        "Rating": rating,
        "Availability": availability})

records[:2]

[{'Title': 'A Light in the Attic',
  'Price (£)': 51.77,
  'Rating': 3,
  'Availability': 'In stock'},
 {'Title': 'Tipping the Velvet',
  'Price (£)': 53.74,
  'Rating': 1,
  'Availability': 'In stock'}]

In [42]:
books_df = pd.DataFrame(records)

display(books_df)

,Title,Price (£),Rating,Availability
0,A Light in the Attic,51.77,3,In stock
1,Tipping the Velvet,53.74,1,In stock
2,Soumission,50.10,1,In stock
3,Sharp Objects,47.82,4,In stock
4,Sapiens: A Brief History of Humankind,54.23,5,In stock
5,The Requiem Red,22.65,1,In stock
6,The Dirty Little Secrets of Getting Your Dream...,33.34,4,In stock
7,The Coming Woman: A Novel Based on the Life of...,17.93,3,In stock
8,The Boys in the Boat: Nine Americans and Their...,22.60,4,In stock
9,The Black Maria,52.15,1,In stock
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,2,In stock
11,Shakespeare's Sonnets,20.66,4,In stock
12,Set Me Free,17.46,5,In stock
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,In stock
14,Rip it Up and Start Again,35.02,5,In stock
15,Our Band Could Be Your Life: Scenes from the A...,57.25,3,In stock
16,Olio,23.88,1,In stock
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,1,In stock
18,Libertarianism for Beginners,51.33,2,In stock
19,It's Only the Himalayas,45.17,2,In stock

In [43]:
filtered_books = books_df[
    (books_df["Rating"] >= 4) &
    (books_df["Price (£)"] <= 20)]

display(filtered_books)

          Title  Price (£)  Rating Availability
12  Set Me Free      17.46       5     In stock

In [44]:
from urllib.parse import urljoin

book_link = first_book.find("h3").find("a")
relative_url = book_link.get("href")
book_url = urljoin(url, relative_url)

print(book_url)

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

In [46]:
book_response = requests.get(book_url)
book_response.raise_for_status()
book_response.encoding = "utf-8"

book_soup = BeautifulSoup(book_response.text, "html.parser")
print(book_soup.prettify()[:1000])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   A Light in the Attic | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="
    It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the

In [47]:
product_table = book_soup.find("table", class_="table table-striped")

print(product_table.prettify())

<table class="table table-striped">
 <tr>
  <th>
   UPC
  </th>
  <td>
   a897fe39b1053632
  </td>
 </tr>
 <tr>
  <th>
   Product Type
  </th>
  <td>
   Books
  </td>
 </tr>
 <tr>
  <th>
   Price (excl. tax)
  </th>
  <td>
   £51.77
  </td>
 </tr>
 <tr>
  <th>
   Price (incl. tax)
  </th>
  <td>
   £51.77
  </td>
 </tr>
 <tr>
  <th>
   Tax
  </th>
  <td>
   £0.00
  </td>
 </tr>
 <tr>
  <th>
   Availability
  </th>
  <td>
   In stock (22 available)
  </td>
 </tr>
 <tr>
  <th>
   Number of reviews
  </th>
  <td>
   0
  </td>
 </tr>
</table>

In [52]:
first_row = product_table.find("tr")
upc = first_row.find("td").get_text(strip=True)

print("UPC:", upc)

UPC: a897fe39b1053632

In [53]:
navigation = book_soup.find("ul", class_="breadcrumb")
navigation_items = navigation.find_all("li")
genre = navigation_items[2].get_text(strip=True)

print("Genre:", genre)

Genre: Poetry

In [55]:
description_section = book_soup.find("div", id="product_description")

print(description_section)

description = description_section.find_next("p").get_text(strip=True)

print("Description:", description)

<div class="sub-header" id="product_description">
<h2>Product Description</h2>
</div>
Description: It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more

In [56]:
records = []

for book in books:
    title = book.find("h3").find("a").get("title")

    price = book.find("p", class_="price_color").get_text(strip=True)
    price = float(price.replace("£", ""))

    rating = book.find("p", class_="star-rating").get("class")[1]
    rating = rating_values[rating]

    availability = book.find("p", class_="instock availability").get_text(strip=True)

    if rating >= 4 and price <= 20:

        relative_url = book.find("h3").find("a").get("href")
        book_url = urljoin(url, relative_url)

        book_response = requests.get(book_url)
        book_response.raise_for_status()
        book_response.encoding = "utf-8"

        book_soup = BeautifulSoup(book_response.text, "html.parser")

        product_table = book_soup.find("table", class_="table table-striped")
        first_row = product_table.find("tr")
        upc = first_row.find("td").get_text(strip=True)

        navigation = book_soup.find("ul", class_="breadcrumb")
        navigation_items = navigation.find_all("li")
        genre = navigation_items[2].get_text(strip=True)

        description_section = book_soup.find("div", id="product_description")

        if description_section:
            description = description_section.find_next("p").get_text(strip=True)
        else:
            description = "Not available"

        records.append({
            "UPC": upc,
            "Title": title,
            "Price (£)": price,
            "Rating": rating,
            "Genre": genre,
            "Availability": availability,
            "Description": description
        })

books_df = pd.DataFrame(records)

display(books_df)

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...

In [61]:
next_page = soup.find("li", class_="next")

print(next_page)

next_link = next_page.find("a").get("href")

print(next_link)

next_url = urljoin(url, next_link)

print(next_url)

<li class="next"><a href="catalogue/page-2.html">next</a></li>
catalogue/page-2.html
https://books.toscrape.com/catalogue/page-2.html

In [65]:
def scrape_books(min_rating, max_price):
    current_url = "https://books.toscrape.com/"
    records = []

    while current_url:
        response = requests.get(current_url)
        response.raise_for_status()
        response.encoding = "utf-8"

        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:
            title = book.find("h3").find("a").get("title")

            price = book.find("p", class_="price_color").get_text(strip=True)
            price = float(price.replace("£", ""))

            rating = book.find("p", class_="star-rating").get("class")[1]
            rating = rating_values[rating]

            availability = book.find("p", class_="instock availability").get_text(strip=True)

            if rating >= min_rating and price <= max_price:
                relative_url = book.find("h3").find("a").get("href")
                book_url = urljoin(current_url, relative_url)

                book_response = requests.get(book_url)
                book_response.raise_for_status()
                book_response.encoding = "utf-8"

                book_soup = BeautifulSoup(book_response.text, "html.parser")

                product_table = book_soup.find("table", class_="table table-striped")
                upc = product_table.find("tr").find("td").get_text(strip=True)

                navigation = book_soup.find("ul", class_="breadcrumb")
                navigation_items = navigation.find_all("li")
                genre = navigation_items[2].get_text(strip=True)

                # Description, if available
                description_section = book_soup.find("div", id="product_description")

                if description_section:
                    description = description_section.find_next("p").get_text(strip=True)
                else:
                    description = "Not available"

                records.append({
                    "UPC": upc,
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": availability,
                    "Description": description
                })

        next_page = soup.find("li", class_="next")

        if next_page:
            next_link = next_page.find("a").get("href")
            current_url = urljoin(current_url, next_link)
        else:
            current_url = None

    return pd.DataFrame(records)

In [66]:
books_df = scrape_books(min_rating=4, max_price=20)

display(books_df)

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock,"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock,A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock,"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock,"Every summer, Rose goes with her mom and dad t..."
...,...,...,...,...,...,...,...
70,9c96cd1329fbd82d,The Zombie Room,19.69,5,Default,In stock,An unlikely bond is forged between three men f...
71,b78deb463531d078,The Silent Wife,12.34,5,Fiction,In stock,A chilling psychological thriller about a marr...
72,4280ac3eab57aa5d,The Girl You Lost,12.29,5,Mystery,In stock,Eighteen years ago your baby daughter was snat...
73,29fc016c459aeb14,The Edge of Reason (Bridget Jones #2),19.18,4,Womens Fiction,In stock,Monday 27 January“7:15 a.m. Hurrah! The wilder...
74,19fec36a1dfb4c16,A Spy's Devotion (The Regency Spies of London #1),16.97,5,Historical Fiction,In stock,"In England’s Regency era, manners and elegance..."

In [69]:
print("Number of matching books:", len(books_df))
print("\nColumns:")
print(books_df.columns)

display(books_df.head())

print("Lowest rating:", books_df["Rating"].min())
print("Highest price:", books_df["Price (£)"].max())

other_books = scrape_books(min_rating=5, max_price=15)

display(other_books.head())

Number of matching books: 75

Columns:
Index(['UPC', 'Title', 'Price (£)', 'Rating', 'Genre', 'Availability',
       'Description'],
      dtype='object')

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock,"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock,A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock,"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock,"Every summer, Rose goes with her mom and dad t..."

Lowest rating: 4
Highest price: 19.69

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,0fa6dceead7ce47a,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",13.61,5,Sequential Art,In stock,THE LONG-AWAITED STORY OF FANGIRLS TAKING ON T...
1,0e691eda369f4e09,Princess Between Worlds (Wide-Awake Princess #5),13.34,5,Fantasy,In stock,Just as Annie and Liam are busy making plans t...
2,3bebf34ee9330cbd,The Third Wave: An Entrepreneur’s Vision of th...,12.61,5,Business,In stock,NEW YORK TIMES BESTSELLERWALL STREET JOURNAL B...
3,d195e7f4ed697350,Agnostic: A Spirited Manifesto,12.51,5,Nonfiction,In stock,A widely admired writer on religion celebrates...
4,6a31307a81e8f3a8,Walt Disney's Alice in Wonderland,12.96,5,Childrens,In stock,The fantastical tale of a young girl chasing h...